primaryColor=#f47d44
secondaryColor=#689789
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@domain.com
loadingLabel=Loading...
loginError=Can't login
chatHeader=Talk to us
startInfo=Please fill the following form to start the chat
startLabel=Start
backLabel=Назад
initMessageBody=Здравствуйте
initMessageAuthor=Оператор
chatInputLabel=Текст сообщения
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=Operator went off-line
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
contactHeader=Тех поддержка
contactInfo=Заполните поля ниже.
contactNameLabel=Имя
contactMailLabel=E-mail
contactQuestionLabel=Ваш вопрос
contactSendLabel=Отправить
contactSuccessHeader=Сообщение отправлено
contactSuccessMessage=Ваш вопрос отправлен. Спасибо
contactErrorHeader=Ошибка
contactErrorMessage=There was an error sending your question
maxConnections=5
messageSound=audio/default.mp3
installed=1
